/**
 * types/database.ts
 * MYOP Healthcare Marketplace
 *
 * DATABASE TYPES — Layer 1 of 3
 *
 * This file contains ONLY types that mirror the PostgreSQL schema exactly.
 * Treat this as if it were generated by `supabase gen types typescript`.
 *
 * Rules:
 *   - No business logic, no app concepts
 *   - Every table has Row / Insert / Update
 *   - Insert: required columns required, DB-defaulted columns optional
 *   - Update: all columns optional, id?: never (PK immutable)
 *   - Enums mirror PostgreSQL enum names exactly
 *
 * When you run `supabase gen types typescript` in the future,
 * replace this file entirely with the generated output.
 */

// =============================================================================
// POSTGRESQL ENUM TYPES
// =============================================================================

export type UserRoleEnum         = 'patient' | 'hospital_staff' | 'admin'
export type BookingModuleEnum    = 'hospital' | 'diagnostic' | 'clinic'
export type AppointmentStatusEnum =
  | 'pending' | 'confirmed' | 'paid' | 'scheduled'
  | 'completed' | 'cancelled' | 'rejected' | 'no_show'
export type OrderStatusEnum      =
  | 'created' | 'attempted' | 'paid' | 'refunded' | 'partially_refunded'
export type PayoutStatusEnum     =
  | 'pending' | 'processing' | 'completed' | 'failed' | 'on_hold'
export type RefundStatusEnum     =
  | 'requested' | 'approved' | 'processing' | 'completed' | 'rejected'
export type NotificationChannelEnum = 'email' | 'in_app' | 'sms'
export type NotificationStatusEnum  =
  | 'pending' | 'sent' | 'delivered' | 'read' | 'failed'
export type ApprovalStatusEnum   = 'pending' | 'approved' | 'rejected' | 'suspended'
export type GenderEnum           = 'male' | 'female' | 'other' | 'prefer_not_to_say'

// =============================================================================
// ROW TYPES — exact shape of each table row returned by SELECT *
// =============================================================================

export interface UserProfileRow {
  id:           string
  role:         UserRoleEnum
  full_name:    string
  avatar_url:   string | null
  is_active:    boolean
  is_onboarded: boolean
  created_at:   string
  updated_at:   string
  deleted_at:   string | null
}

export interface PatientProfileRow {
  id:                      string
  date_of_birth:           string | null
  gender:                  GenderEnum | null
  phone:                   string | null
  blood_group:             string | null
  address:                 string | null
  city:                    string | null
  state:                   string | null
  pincode:                 string | null
  emergency_contact_name:  string | null
  emergency_contact_phone: string | null
  created_at:              string
  updated_at:              string
  deleted_at:              string | null
}

export interface HospitalRow {
  id:                      string
  module:                  BookingModuleEnum
  approval_status:         ApprovalStatusEnum
  name:                    string
  slug:                    string
  logo_url:                string | null
  description:             string | null
  email:                   string
  phone:                   string
  website:                 string | null
  address_line1:           string
  address_line2:           string | null
  city:                    string
  state:                   string
  pincode:                 string
  latitude:                number | null
  longitude:               number | null
  platform_commission_pct: number
  bank_account_number:     string | null
  bank_ifsc_code:          string | null
  bank_account_name:       string | null
  razorpay_account_id:     string | null
  approved_at:             string | null
  approved_by:             string | null
  // --- Migration 003 additions ---
  rejection_reason:        string | null
  suspended_at:            string | null
  suspended_by:            string | null
  created_at:              string
  updated_at:              string
  deleted_at:              string | null
}

export interface HospitalStaffRow {
  id:          string
  hospital_id: string
  user_id:     string
  role_label:  string
  is_active:   boolean
  created_at:  string
  updated_at:  string
  deleted_at:  string | null
}

export interface DepartmentRow {
  id:          string
  hospital_id: string
  name:        string
  description: string | null
  icon_url:    string | null
  is_active:   boolean
  created_at:  string
  updated_at:  string
  deleted_at:  string | null
}

export interface DoctorRow {
  id:                  string
  hospital_id:         string
  department_id:       string | null
  // --- Migration 004 addition ---
  slug:                string
  full_name:           string
  photo_url:           string | null
  gender:              'male' | 'female' | 'other' | null
  specialisation:      string
  qualification:       string
  registration_number: string
  experience_years:    number
  languages:           string[] | null
  bio:                 string | null
  consultation_fee:    number
  is_active:           boolean
  created_at:          string
  updated_at:          string
  deleted_at:          string | null
}

export interface DoctorScheduleRow {
  id:                  string
  doctor_id:           string
  hospital_id:         string
  day_of_week:         0 | 1 | 2 | 3 | 4 | 5 | 6
  start_time:          string
  end_time:            string
  slot_duration_mins:  number
  max_patients:        number
  is_active:           boolean
  effective_from:      string
  effective_until:     string | null
  created_at:          string
  updated_at:          string
  deleted_at:          string | null
}

export interface AppointmentSlotRow {
  id:            string
  doctor_id:     string
  hospital_id:   string
  schedule_id:   string | null
  slot_start:    string
  slot_end:      string
  max_bookings:  number
  booked_count:  number
  is_available:  boolean
  is_blocked:    boolean
  created_at:    string
  updated_at:    string
  deleted_at:    string | null
}

export interface ServiceRow {
  id:              string
  hospital_id:     string
  module:          BookingModuleEnum
  name:            string
  description:     string | null
  code:            string | null
  category:        string | null
  price:           number
  duration_mins:   number | null
  preparation:     string | null
  report_tat_hrs:  number | null
  is_active:       boolean
  is_home_collection: boolean
  created_at:      string
  updated_at:      string
  deleted_at:      string | null
}

export interface AppointmentRow {
  id:                  string
  module:              BookingModuleEnum
  status:              AppointmentStatusEnum
  patient_id:          string
  hospital_id:         string
  doctor_id:           string | null
  slot_id:             string | null
  service_id:          string | null
  department_id:       string | null
  scheduled_at:        string | null
  completed_at:        string | null
  cancelled_at:        string | null
  fee_amount:          number
  platform_commission: number
  hospital_earning:    number
  patient_notes:       string | null
  chief_complaint:     string | null
  staff_notes:         string | null
  cancellation_reason: string | null
  confirmed_at:        string | null
  confirmed_by:        string | null
  rejected_at:         string | null
  rejected_by:         string | null
  created_at:          string
  updated_at:          string
  deleted_at:          string | null
}

export interface OrderRow {
  id:                   string
  appointment_id:       string
  patient_id:           string
  razorpay_order_id:    string
  razorpay_payment_id:  string | null
  razorpay_signature:   string | null
  amount:               number
  currency:             string
  status:               OrderStatusEnum
  payment_method:       string | null
  payment_captured_at:  string | null
  notes:                Record<string, unknown> | null
  created_at:           string
  updated_at:           string
  deleted_at:           string | null
}

export interface RefundRow {
  id:                  string
  order_id:            string
  appointment_id:      string
  requested_by:        string
  amount:              number
  status:              RefundStatusEnum
  reason:              string
  reviewed_by:         string | null
  reviewed_at:         string | null
  admin_notes:         string | null
  razorpay_refund_id:  string | null
  processed_at:        string | null
  created_at:          string
  updated_at:          string
  deleted_at:          string | null
}

export interface PayoutRow {
  id:                  string
  hospital_id:         string
  initiated_by:        string | null
  period_start:        string
  period_end:          string
  gross_amount:        number
  deductions:          number
  net_amount:          number
  status:              PayoutStatusEnum
  notes:               string | null
  razorpay_payout_id:  string | null
  transferred_at:      string | null
  failure_reason:      string | null
  created_at:          string
  updated_at:          string
  deleted_at:          string | null
}

export interface PayoutItemRow {
  id:             string
  payout_id:      string
  appointment_id: string
  order_id:       string
  gross_amount:   number
  commission:     number
  net_amount:     number
  created_at:     string
}

export interface ConversationRow {
  id:             string
  appointment_id: string
  module:         BookingModuleEnum
  patient_id:     string
  hospital_id:    string
  is_active:      boolean
  last_message_at: string | null
  created_at:     string
  updated_at:     string
  deleted_at:     string | null
}

export interface ChatMessageRow {
  id:              string
  conversation_id: string
  sender_id:       string
  content:         string
  is_read:         boolean
  read_at:         string | null
  attachment_url:  string | null
  attachment_type: string | null
  created_at:      string
  updated_at:      string
  deleted_at:      string | null
}

export interface NotificationRow {
  id:               string
  user_id:          string
  channel:          NotificationChannelEnum
  status:           NotificationStatusEnum
  title:            string
  body:             string
  action_url:       string | null
  appointment_id:   string | null
  order_id:         string | null
  resend_message_id: string | null
  sent_at:          string | null
  read_at:          string | null
  failed_at:        string | null
  failure_reason:   string | null
  created_at:       string
  updated_at:       string
  deleted_at:       string | null
}

export interface AuditLogRow {
  id:         string
  actor_id:   string | null
  action:     string
  table_name: string
  row_id:     string
  old_data:   Record<string, unknown> | null
  new_data:   Record<string, unknown> | null
  ip_address: string | null
  user_agent: string | null
  created_at: string
}

// =============================================================================
// DATABASE TYPE MAP
// =============================================================================

export type Database = {
  public: {
    Tables: {

      user_profiles: {
        Row: UserProfileRow
        Insert: {
          id:            string
          role?:         UserRoleEnum
          full_name:     string
          avatar_url?:   string | null
          is_active?:    boolean
          is_onboarded?: boolean
          created_at?:   string
          updated_at?:   string
          deleted_at?:   string | null
        }
        Update: {
          id?:           never
          role?:         UserRoleEnum
          full_name?:    string
          avatar_url?:   string | null
          is_active?:    boolean
          is_onboarded?: boolean
          updated_at?:   string
          deleted_at?:   string | null
        }
      }

      patient_profiles: {
        Row: PatientProfileRow
        Insert: {
          id:                       string
          date_of_birth?:           string | null
          gender?:                  GenderEnum | null
          phone?:                   string | null
          blood_group?:             string | null
          address?:                 string | null
          city?:                    string | null
          state?:                   string | null
          pincode?:                 string | null
          emergency_contact_name?:  string | null
          emergency_contact_phone?: string | null
          created_at?:              string
          updated_at?:              string
          deleted_at?:              string | null
        }
        Update: {
          id?:                      never
          date_of_birth?:           string | null
          gender?:                  GenderEnum | null
          phone?:                   string | null
          blood_group?:             string | null
          address?:                 string | null
          city?:                    string | null
          state?:                   string | null
          pincode?:                 string | null
          emergency_contact_name?:  string | null
          emergency_contact_phone?: string | null
          updated_at?:              string
          deleted_at?:              string | null
        }
      }

      hospitals: {
        Row: HospitalRow
        Insert: {
          id?:                      string
          module:                   BookingModuleEnum
          approval_status?:         ApprovalStatusEnum
          name:                     string
          slug:                     string
          logo_url?:                string | null
          description?:             string | null
          email:                    string
          phone:                    string
          website?:                 string | null
          address_line1:            string
          address_line2?:           string | null
          city:                     string
          state:                    string
          pincode:                  string
          latitude?:                number | null
          longitude?:               number | null
          platform_commission_pct?: number
          bank_account_number?:     string | null
          bank_ifsc_code?:          string | null
          bank_account_name?:       string | null
          razorpay_account_id?:     string | null
          approved_at?:             string | null
          approved_by?:             string | null
          rejection_reason?:        string | null
          suspended_at?:            string | null
          suspended_by?:            string | null
          created_at?:              string
          updated_at?:              string
          deleted_at?:              string | null
        }
        Update: {
          id?:                      never
          module?:                  BookingModuleEnum
          approval_status?:         ApprovalStatusEnum
          name?:                    string
          slug?:                    string
          logo_url?:                string | null
          description?:             string | null
          email?:                   string
          phone?:                   string
          website?:                 string | null
          address_line1?:           string
          address_line2?:           string | null
          city?:                    string
          state?:                   string
          pincode?:                 string
          latitude?:                number | null
          longitude?:               number | null
          platform_commission_pct?: number
          bank_account_number?:     string | null
          bank_ifsc_code?:          string | null
          bank_account_name?:       string | null
          razorpay_account_id?:     string | null
          approved_at?:             string | null
          approved_by?:             string | null
          rejection_reason?:        string | null
          suspended_at?:            string | null
          suspended_by?:            string | null
          updated_at?:              string
          deleted_at?:              string | null
        }
      }

      hospital_staff: {
        Row: HospitalStaffRow
        Insert: {
          id?:          string
          hospital_id:  string
          user_id:      string
          role_label?:  string
          is_active?:   boolean
          created_at?:  string
          updated_at?:  string
          deleted_at?:  string | null
        }
        Update: {
          id?:          never
          hospital_id?: string
          user_id?:     string
          role_label?:  string
          is_active?:   boolean
          updated_at?:  string
          deleted_at?:  string | null
        }
      }

      departments: {
        Row: DepartmentRow
        Insert: {
          id?:          string
          hospital_id:  string
          name:         string
          description?: string | null
          icon_url?:    string | null
          is_active?:   boolean
          created_at?:  string
          updated_at?:  string
          deleted_at?:  string | null
        }
        Update: {
          id?:          never
          hospital_id?: string
          name?:        string
          description?: string | null
          icon_url?:    string | null
          is_active?:   boolean
          updated_at?:  string
          deleted_at?:  string | null
        }
      }

      doctors: {
        Row: DoctorRow
        Insert: {
          id?:                   string
          hospital_id:           string
          department_id?:        string | null
          slug?:                 string        // auto-generated by trigger if omitted
          full_name:             string
          photo_url?:            string | null
          gender?:               'male' | 'female' | 'other' | null
          specialisation:        string
          qualification:         string
          registration_number:   string
          experience_years?:     number
          languages?:            string[] | null
          bio?:                  string | null
          consultation_fee:      number
          is_active?:            boolean
          created_at?:           string
          updated_at?:           string
          deleted_at?:           string | null
        }
        Update: {
          id?:                   never
          hospital_id?:          string
          department_id?:        string | null
          slug?:                 string
          full_name?:            string
          photo_url?:            string | null
          gender?:               'male' | 'female' | 'other' | null
          specialisation?:       string
          qualification?:        string
          registration_number?:  string
          experience_years?:     number
          languages?:            string[] | null
          bio?:                  string | null
          consultation_fee?:     number
          is_active?:            boolean
          updated_at?:           string
          deleted_at?:           string | null
        }
      }

      doctor_schedules: {
        Row: DoctorScheduleRow
        Insert: {
          id?:                  string
          doctor_id:            string
          hospital_id:          string
          day_of_week:          0 | 1 | 2 | 3 | 4 | 5 | 6
          start_time:           string
          end_time:             string
          slot_duration_mins?:  number
          max_patients?:        number
          is_active?:           boolean
          effective_from?:      string
          effective_until?:     string | null
          created_at?:          string
          updated_at?:          string
          deleted_at?:          string | null
        }
        Update: {
          id?:                  never
          doctor_id?:           string
          hospital_id?:         string
          day_of_week?:         0 | 1 | 2 | 3 | 4 | 5 | 6
          start_time?:          string
          end_time?:            string
          slot_duration_mins?:  number
          max_patients?:        number
          is_active?:           boolean
          effective_from?:      string
          effective_until?:     string | null
          updated_at?:          string
          deleted_at?:          string | null
        }
      }

      appointment_slots: {
        Row: AppointmentSlotRow
        Insert: {
          id?:           string
          doctor_id:     string
          hospital_id:   string
          schedule_id?:  string | null
          slot_start:    string
          slot_end:      string
          max_bookings?: number
          booked_count?: number
          is_available?: boolean
          is_blocked?:   boolean
          created_at?:   string
          updated_at?:   string
          deleted_at?:   string | null
        }
        Update: {
          id?:           never
          doctor_id?:    string
          hospital_id?:  string
          schedule_id?:  string | null
          slot_start?:   string
          slot_end?:     string
          max_bookings?: number
          booked_count?: number
          is_available?: boolean
          is_blocked?:   boolean
          updated_at?:   string
          deleted_at?:   string | null
        }
      }

      services: {
        Row: ServiceRow
        Insert: {
          id?:               string
          hospital_id:       string
          module:            BookingModuleEnum
          name:              string
          description?:      string | null
          code?:             string | null
          category?:         string | null
          price:             number
          duration_mins?:    number | null
          preparation?:      string | null
          report_tat_hrs?:   number | null
          is_active?:        boolean
          is_home_collection?: boolean
          created_at?:       string
          updated_at?:       string
          deleted_at?:       string | null
        }
        Update: {
          id?:               never
          hospital_id?:      string
          module?:           BookingModuleEnum
          name?:             string
          description?:      string | null
          code?:             string | null
          category?:         string | null
          price?:            number
          duration_mins?:    number | null
          preparation?:      string | null
          report_tat_hrs?:   number | null
          is_active?:        boolean
          is_home_collection?: boolean
          updated_at?:       string
          deleted_at?:       string | null
        }
      }

      appointments: {
        Row: AppointmentRow
        Insert: {
          id?:                   string
          module:                BookingModuleEnum
          status?:               AppointmentStatusEnum
          patient_id:            string
          hospital_id:           string
          doctor_id?:            string | null
          slot_id?:              string | null
          service_id?:           string | null
          department_id?:        string | null
          scheduled_at?:         string | null
          completed_at?:         string | null
          cancelled_at?:         string | null
          fee_amount:            number
          platform_commission?:  number
          hospital_earning?:     number
          patient_notes?:        string | null
          chief_complaint?:      string | null
          staff_notes?:          string | null
          cancellation_reason?:  string | null
          confirmed_at?:         string | null
          confirmed_by?:         string | null
          rejected_at?:          string | null
          rejected_by?:          string | null
          created_at?:           string
          updated_at?:           string
          deleted_at?:           string | null
        }
        Update: {
          id?:                   never
          module?:               BookingModuleEnum
          status?:               AppointmentStatusEnum
          patient_id?:           string
          hospital_id?:          string
          doctor_id?:            string | null
          slot_id?:              string | null
          service_id?:           string | null
          department_id?:        string | null
          scheduled_at?:         string | null
          completed_at?:         string | null
          cancelled_at?:         string | null
          fee_amount?:           number
          platform_commission?:  number
          hospital_earning?:     number
          patient_notes?:        string | null
          chief_complaint?:      string | null
          staff_notes?:          string | null
          cancellation_reason?:  string | null
          confirmed_at?:         string | null
          confirmed_by?:         string | null
          rejected_at?:          string | null
          rejected_by?:          string | null
          updated_at?:           string
          deleted_at?:           string | null
        }
      }

      orders: {
        Row: OrderRow
        Insert: {
          id?:                    string
          appointment_id:         string
          patient_id:             string
          razorpay_order_id:      string
          razorpay_payment_id?:   string | null
          razorpay_signature?:    string | null
          amount:                 number
          currency?:              string
          status?:                OrderStatusEnum
          payment_method?:        string | null
          payment_captured_at?:   string | null
          notes?:                 Record<string, unknown> | null
          created_at?:            string
          updated_at?:            string
          deleted_at?:            string | null
        }
        Update: {
          id?:                    never
          appointment_id?:        string
          patient_id?:            string
          razorpay_order_id?:     string
          razorpay_payment_id?:   string | null
          razorpay_signature?:    string | null
          amount?:                number
          currency?:              string
          status?:                OrderStatusEnum
          payment_method?:        string | null
          payment_captured_at?:   string | null
          notes?:                 Record<string, unknown> | null
          updated_at?:            string
          deleted_at?:            string | null
        }
      }

      refunds: {
        Row: RefundRow
        Insert: {
          id?:                   string
          order_id:              string
          appointment_id:        string
          requested_by:          string
          amount:                number
          status?:               RefundStatusEnum
          reason:                string
          reviewed_by?:          string | null
          reviewed_at?:          string | null
          admin_notes?:          string | null
          razorpay_refund_id?:   string | null
          processed_at?:         string | null
          created_at?:           string
          updated_at?:           string
          deleted_at?:           string | null
        }
        Update: {
          id?:                   never
          order_id?:             string
          appointment_id?:       string
          requested_by?:         string
          amount?:               number
          status?:               RefundStatusEnum
          reason?:               string
          reviewed_by?:          string | null
          reviewed_at?:          string | null
          admin_notes?:          string | null
          razorpay_refund_id?:   string | null
          processed_at?:         string | null
          updated_at?:           string
          deleted_at?:           string | null
        }
      }

      payouts: {
        Row: PayoutRow
        Insert: {
          id?:                  string
          hospital_id:          string
          initiated_by?:        string | null
          period_start:         string
          period_end:           string
          gross_amount:         number
          deductions?:          number
          net_amount:           number
          status?:              PayoutStatusEnum
          notes?:               string | null
          razorpay_payout_id?:  string | null
          transferred_at?:      string | null
          failure_reason?:      string | null
          created_at?:          string
          updated_at?:          string
          deleted_at?:          string | null
        }
        Update: {
          id?:                  never
          hospital_id?:         string
          initiated_by?:        string | null
          period_start?:        string
          period_end?:          string
          gross_amount?:        number
          deductions?:          number
          net_amount?:          number
          status?:              PayoutStatusEnum
          notes?:               string | null
          razorpay_payout_id?:  string | null
          transferred_at?:      string | null
          failure_reason?:      string | null
          updated_at?:          string
          deleted_at?:          string | null
        }
      }

      payout_items: {
        Row: PayoutItemRow
        Insert: {
          id?:            string
          payout_id:      string
          appointment_id: string
          order_id:       string
          gross_amount:   number
          commission:     number
          net_amount:     number
          created_at?:    string
        }
        Update: {
          id?:            never
          payout_id?:     string
          appointment_id?: string
          order_id?:      string
          gross_amount?:  number
          commission?:    number
          net_amount?:    number
        }
      }

      conversations: {
        Row: ConversationRow
        Insert: {
          id?:              string
          appointment_id:   string
          module:           BookingModuleEnum
          patient_id:       string
          hospital_id:      string
          is_active?:       boolean
          last_message_at?: string | null
          created_at?:      string
          updated_at?:      string
          deleted_at?:      string | null
        }
        Update: {
          id?:              never
          appointment_id?:  string
          module?:          BookingModuleEnum
          patient_id?:      string
          hospital_id?:     string
          is_active?:       boolean
          last_message_at?: string | null
          updated_at?:      string
          deleted_at?:      string | null
        }
      }

      chat_messages: {
        Row: ChatMessageRow
        Insert: {
          id?:              string
          conversation_id:  string
          sender_id:        string
          content:          string
          is_read?:         boolean
          read_at?:         string | null
          attachment_url?:  string | null
          attachment_type?: string | null
          created_at?:      string
          updated_at?:      string
          deleted_at?:      string | null
        }
        Update: {
          id?:              never
          conversation_id?: string
          sender_id?:       string
          content?:         string
          is_read?:         boolean
          read_at?:         string | null
          attachment_url?:  string | null
          attachment_type?: string | null
          updated_at?:      string
          deleted_at?:      string | null
        }
      }

      notifications: {
        Row: NotificationRow
        Insert: {
          id?:               string
          user_id:           string
          channel?:          NotificationChannelEnum
          status?:           NotificationStatusEnum
          title:             string
          body:              string
          action_url?:       string | null
          appointment_id?:   string | null
          order_id?:         string | null
          resend_message_id?: string | null
          sent_at?:          string | null
          read_at?:          string | null
          failed_at?:        string | null
          failure_reason?:   string | null
          created_at?:       string
          updated_at?:       string
          deleted_at?:       string | null
        }
        Update: {
          id?:               never
          user_id?:          string
          channel?:          NotificationChannelEnum
          status?:           NotificationStatusEnum
          title?:            string
          body?:             string
          action_url?:       string | null
          appointment_id?:   string | null
          order_id?:         string | null
          resend_message_id?: string | null
          sent_at?:          string | null
          read_at?:          string | null
          failed_at?:        string | null
          failure_reason?:   string | null
          updated_at?:       string
          deleted_at?:       string | null
        }
      }

      audit_logs: {
        Row: AuditLogRow
        Insert: {
          id?:         string
          actor_id?:   string | null
          action:      string
          table_name:  string
          row_id:      string
          old_data?:   Record<string, unknown> | null
          new_data?:   Record<string, unknown> | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: never  // audit_logs are immutable
      }

    }
    Enums: {
      user_role:            UserRoleEnum
      booking_module:       BookingModuleEnum
      appointment_status:   AppointmentStatusEnum
      order_status:         OrderStatusEnum
      payout_status:        PayoutStatusEnum
      refund_status:        RefundStatusEnum
      notification_channel: NotificationChannelEnum
      notification_status:  NotificationStatusEnum
      approval_status:      ApprovalStatusEnum
    }
  }
}